version: "2"
services:
        elasticsearch:
                image: elasticsearch:7.9.1
                environment:
                        - http.host=0.0.0.0
                        - discovery.type=single-node
                        - script.allowed_types=inline
                        - thread_pool.search.queue_size=100000
                        - thread_pool.write.queue_size=10000
                volumes:
                        - /home/ubuntu/thehive:/usr/share/elasticsearch/data
        cortex:
                image: thehiveproject/cortex:latest
                depends_on:
                        - elasticsearch
                ports:
                        - "0.0.0.0:9001:9001"
        thehive:
                image: thehiveproject/thehive:latest
                depends_on:
                        - elasticsearch
                        - cortex
                ports:
                        - "0.0.0.0:9000:9000"
                command: --cortex-port 9001
